### List Instructors
GET http://127.0.0.1:8000/api/instructors/


### Create Instructors
POST http://127.0.0.1:8000/api/instructors/
Content-Type: application/json

{
    "name": "Narender",
    "gender": "Male",
    "date_of_birth": "1998-11-17",
    "department": "CSE",
    "email": "narender@gmail.com",
    "contact_number": "9876543210"
}



### List Single Instructors
GET http://127.0.0.1:8000/api/instructors/2



### Update Instructors
PATCH http://127.0.0.1:8000/api/instructors/2/
Content-Type: application/json

{
    "department": "Civil"
}



### Delete Instructors
DELETE http://127.0.0.1:8000/api/instructors/2/





### List Courses
GET http://127.0.0.1:8000/api/courses/


### Create Courses
POST http://127.0.0.1:8000/api/courses/
Content-Type: application/json

{
    "course_code": "9743",
    "course_name": "Full Stack Web Development",
    "department": "CSE",
    "credits": 100,
    "description": "Learn Complete Full Stack Web Development"
}



### List Single Courses
GET http://127.0.0.1:8000/api/courses/2



### Update Courses
PATCH http://127.0.0.1:8000/api/courses/2/
Content-Type: application/json

{
    "department": "Civil"
}



### Delete Courses
DELETE http://127.0.0.1:8000/api/courses/2/
